"""add NGO SaaS foundation

Revision ID: 5a9b0c7a4897
Revises: 
Create Date: 2026-07-25 21:46:07.396529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9b0c7a4897'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_sessions_agency_id'), 'access_sessions', ['agency_id'], unique=False)
    op.create_index(op.f('ix_access_sessions_expires_at'), 'access_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_access_sessions_token_hash'), 'access_sessions', ['token_hash'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_agency_id'), 'audit_events', ['agency_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact', sa.JSON(), nullable=True),
    sa.Column('consent_to_contact', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_agency_id'), 'complaints', ['agency_id'], unique=False)
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_service_id'), 'complaints', ['service_id'], unique=False)
    op.create_index(op.f('ix_complaints_severity'), 'complaints', ['severity'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['access_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agency_id'), 'conversations', ['agency_id'], unique=False)
    op.create_index(op.f('ix_conversations_scope'), 'conversations', ['scope'], unique=False)
    op.create_index(op.f('ix_conversations_service_id'), 'conversations', ['service_id'], unique=False)
    op.create_table('issue_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('representative_items', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_clusters_agency_id'), 'issue_clusters', ['agency_id'], unique=False)
    op.create_index(op.f('ix_issue_clusters_category'), 'issue_clusters', ['category'], unique=False)
    op.create_index(op.f('ix_issue_clusters_last_seen_at'), 'issue_clusters', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_issue_clusters_service_id'), 'issue_clusters', ['service_id'], unique=False)
    op.create_index(op.f('ix_issue_clusters_source_kind'), 'issue_clusters', ['source_kind'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answer_status', sa.String(length=30), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_answer_status'), 'chat_messages', ['answer_status'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_agency_id'), 'insights', ['agency_id'], unique=False)
    op.create_index(op.f('ix_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_insights_status'), 'insights', ['status'], unique=False)
    op.add_column('agencies', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('agencies', sa.Column('sector', sa.String(length=80), nullable=False, server_default='NGO'))
    op.add_column('agencies', sa.Column('primary_color', sa.String(length=30), nullable=False, server_default='#175CD3'))
    op.add_column('agencies', sa.Column('accent_color', sa.String(length=30), nullable=False, server_default='#12B76A'))
    op.add_column('agencies', sa.Column('terminology', sa.JSON(), nullable=False, server_default=sa.text("json_build_object('service_singular', 'Program', 'service_plural', 'Programs')")))
    op.add_column('agencies', sa.Column('features', sa.JSON(), nullable=False, server_default=sa.text("json_build_object('public_chat', true, 'complaints', true, 'employee_assistant', true, 'insights', true)")))
    op.add_column('agencies', sa.Column('contact', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))
    op.add_column('agencies', sa.Column('access_code_hash', sa.Text(), nullable=True))
    op.add_column('agencies', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('agencies', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.execute("UPDATE agencies SET slug = lower(short_code) WHERE slug IS NULL")
    op.create_index(op.f('ix_agencies_slug'), 'agencies', ['slug'], unique=True)
    op.add_column('chunks', sa.Column('agency_id', sa.String(length=36), nullable=True))
    op.add_column('chunks', sa.Column('visibility', sa.String(length=20), nullable=False, server_default='PUBLIC'))
    op.add_column('chunks', sa.Column('approval_status', sa.String(length=20), nullable=False, server_default='APPROVED'))
    op.execute("""
        UPDATE chunks
        SET agency_id = sources.agency_id
        FROM sources
        WHERE chunks.source_id = sources.id
    """)
    op.create_index(op.f('ix_chunks_agency_id'), 'chunks', ['agency_id'], unique=False)
    op.create_index(op.f('ix_chunks_approval_status'), 'chunks', ['approval_status'], unique=False)
    op.create_index(op.f('ix_chunks_visibility'), 'chunks', ['visibility'], unique=False)
    op.create_foreign_key('fk_chunks_agency_id_agencies', 'chunks', 'agencies', ['agency_id'], ['id'], ondelete='CASCADE')
    op.add_column('sources', sa.Column('visibility', sa.String(length=20), nullable=False, server_default='PUBLIC'))
    op.add_column('sources', sa.Column('approval_status', sa.String(length=20), nullable=False, server_default='APPROVED'))
    op.add_column('sources', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('sources', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('sources', sa.Column('checksum', sa.String(length=64), nullable=True))
    op.add_column('sources', sa.Column('processing_status', sa.String(length=20), nullable=False, server_default='READY'))
    op.add_column('sources', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('sources', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_sources_approval_status'), 'sources', ['approval_status'], unique=False)
    op.create_index(op.f('ix_sources_visibility'), 'sources', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_visibility'), table_name='sources')
    op.drop_index(op.f('ix_sources_approval_status'), table_name='sources')
    op.drop_column('sources', 'updated_at')
    op.drop_column('sources', 'created_at')
    op.drop_column('sources', 'processing_status')
    op.drop_column('sources', 'checksum')
    op.drop_column('sources', 'version')
    op.drop_column('sources', 'department')
    op.drop_column('sources', 'approval_status')
    op.drop_column('sources', 'visibility')
    op.drop_constraint('fk_chunks_agency_id_agencies', 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_visibility'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_approval_status'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_agency_id'), table_name='chunks')
    op.drop_column('chunks', 'approval_status')
    op.drop_column('chunks', 'visibility')
    op.drop_column('chunks', 'agency_id')
    op.drop_index(op.f('ix_agencies_slug'), table_name='agencies')
    op.drop_column('agencies', 'created_at')
    op.drop_column('agencies', 'is_active')
    op.drop_column('agencies', 'access_code_hash')
    op.drop_column('agencies', 'contact')
    op.drop_column('agencies', 'features')
    op.drop_column('agencies', 'terminology')
    op.drop_column('agencies', 'accent_color')
    op.drop_column('agencies', 'primary_color')
    op.drop_column('agencies', 'sector')
    op.drop_column('agencies', 'slug')
    op.drop_index(op.f('ix_insights_status'), table_name='insights')
    op.drop_index(op.f('ix_insights_created_at'), table_name='insights')
    op.drop_index(op.f('ix_insights_agency_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_answer_status'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_issue_clusters_source_kind'), table_name='issue_clusters')
    op.drop_index(op.f('ix_issue_clusters_service_id'), table_name='issue_clusters')
    op.drop_index(op.f('ix_issue_clusters_last_seen_at'), table_name='issue_clusters')
    op.drop_index(op.f('ix_issue_clusters_category'), table_name='issue_clusters')
    op.drop_index(op.f('ix_issue_clusters_agency_id'), table_name='issue_clusters')
    op.drop_table('issue_clusters')
    op.drop_index(op.f('ix_conversations_service_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_scope'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agency_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_severity'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_service_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_agency_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_agency_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_access_sessions_token_hash'), table_name='access_sessions')
    op.drop_index(op.f('ix_access_sessions_expires_at'), table_name='access_sessions')
    op.drop_index(op.f('ix_access_sessions_agency_id'), table_name='access_sessions')
    op.drop_table('access_sessions')
    # ### end Alembic commands ###
